version 0.2 stabilization

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -28,9 +28,6 @@ jobs:
       - name: Tests
         run: |
          emacs -Q --batch -l ert.el -l selected-window-contrast.el -l swc2-tests.el -f ert-run-tests-batch-and-exit
-      - name: Tests old
-        run: |
-         emacs -Q --batch -l ert.el -l selected-window-contrast-old.el -l swc-old-tests.el -f ert-run-tests-batch-and-exit
       - name: Run
         env:
           LOCAL_REPO: ${{ github.workspace }}
@@ -39,29 +36,18 @@ jobs:
           # set this to false (or remove it) if the package isn't on MELPA:
           EXIST_OK: true
         run: |
-          if make -C ~/melpazoid |& tee output.log ; then
-            [ $? -ne 0 ] && { echo "Error detected, failing workflow"; exit 1; }
-            if grep -v 'Warning: argument ' output.log | grep -q "Warning"; then
-              echo "Warnings detected, failing workflow"
-              exit 1
-            fi
-            if grep -q "Warning" output.log ; then
-              echo "Warnings detected, failing workflow"
-              exit 1
-            fi
-            if grep -q ': error: ' output.log ; then
-              echo "Error detected, failing workflow"
-              exit 1
-            fi
-            if grep -q ' with checkdoc ' output.log ; then
-              echo "Checkdoc warning detected, failing workflow"
-              exit 1
-            fi
-            if grep -q 'much wider than 80 characters' output.log ; then
-              echo "Checkdoc warning detected, failing workflow"
-              exit 1
-            fi
-          else
-            echo "Make command failed, failing workflow"
-            exit 1
+          echo $GITHUB_REF
+          make -C ~/melpazoid |& tee output.log
+          [ $? -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+          if grep -q "Warning" output.log ; then
+            echo "Warnings detected, failing workflow" ; exit 1
+          fi
+          if grep -q ': error: ' output.log ; then
+            echo "Error detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with checkdoc ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q 'much wider than 80 characters' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
