small fixs in code 2

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -57,6 +57,10 @@ jobs:
               echo "Checkdoc warning detected, failing workflow"
               exit 1
             fi
+            if grep -q 'much wider than 80 characters' output.log ; then
+              echo "Checkdoc warning detected, failing workflow"
+              exit 1
+            fi
           else
             echo "Make command failed, failing workflow"
             exit 1
